apiVersion: v1
kind: Service
metadata:
  name: config-map-service
  labels:
    app.kubernetes.io/name: config-map-service
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: config-map-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map-service
  labels:
    app.kubernetes.io/name: config-map-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-map-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-map-service
    spec:
      containers:
        - name: config-map-service
          image: "hellowoodes/spring-cloud-k8s-config-map:1.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: dev
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP